---
- hosts: all
  user: "{{ host_user }}"
  become: yes
  become_method: sudo
  vars_files:
    - "vars.yml"
  roles:
  - { role: elasticsearch, tags: 'elasticsearch-setup' }
  - { role: kibana, tags: 'kibana-setup' }
  - { role: logstash, tags: 'logstash-setup' }
  - nginx